dist: bionic

language: java

matrix:
  fast_finish: true
  include:
    - jdk: openjdk11
    - jdk: openjdk14
    - jdk: openjdk-ea

  allow_failures:
    - jdk: openjdk14
    - jdk: openjdk-ea

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y default-jdk
