dist: bionic

language: java

matrix:
  fast_finish: true
  include:
    - jdk: openjdk11
      env: _JAVA_OPTIONS=-Djdk.tls.client.protocols=TLSv1.2
    - jdk: openjdk14
    - jdk: openjdk-ea

  allow_failures:
    - jdk: openjdk14
    - jdk: openjdk-ea
